
# Site settings
title: Car Design
email: charlie_mtz.98@hotmail.com
description: The best articles about the newest cars.
url: "http://CarDesignLifeCharli.com" # the base hostname & protocol for your site
twitter_username: CharlessMtz

# Build settings
markdown: kramdown
permalink: /:title

port: 4000
