# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Car Design
email: charlie_mtz.98@hotmail.com
description: The best articles about the newest cars.
url: "http://CarDesignLife.com" # the base hostname & protocol for your site
twitter_username: CharlessMtz

# Build settings
markdown: kramdown
permalink: /:title
